export HISTCONTROL=erasedups
export HISTSIZE=10000
export EDITOR=vim
shopt -s histappend
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# function parse_git_branch {
#   ref=$(git-symbolic-ref HEAD 2> /dev/null) || return
#     echo "("${ref#refs/heads/}")"
#   }

function parse_git_branch {
  local ref=$(git symbolic-ref HEAD 2> /dev/null)
    if [[ -n $ref ]]; then
      echo `expr "$ref" : 'refs/heads/\(.*\)'`
    fi
  }

PS1="\$(parse_git_branch)> "

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

function bundle_open {
  vim `bundle show $*`
}

alias tmux-set-current-path='pwd | xargs tmux set-option default-path'

# alias emacs='/usr/local/Cellar/emacs/24.3/bin/emacs'

export RUBY_HEAP_MIN_SLOTS=600000
export RUBY_GC_MALLOC_LIMIT=59000000
export RUBY_GC_HEAP_INIT_SLOTS=100000

export TMUX_SESSION=$USER
export TMUX_SOCKET_PATH="/tmp/jalons-mbp"

function curl-switchfly {
  curl "https://groupon-uat.switchfly.com/api/api.cfm" "${@}"
}

export PATH=$PATH:$HOME/.rvm/bin

if [[ -z $TMUX ]]; then
  # ** TMUX ATULOGIN **
  # Check for existing session and attach if present
  tmux -S $TMUX_SOCKET_PATH has-session -t $TMUX_SESSION &>/dev/null
  if [[ $? -ne 0 ]]; then
    tmux -S $TMUX_SOCKET_PATH new-session -d -s $TMUX_SESSION
  fi
  tmux -S $TMUX_SOCKET_PATH attach-session -t $TMUX_SESSION &>/dev/null
fi
